apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fdtest
  template:
    metadata:
      labels:
        app: fdtest
    spec:
      containers:
      - image: {{ $.Values.werf.image.fdtest }}
      - name: fdtest